//test get all
GET http://localhost:5000/api/annunci

###
//test get by id
GET http://localhost:5000/api/annunci/645cf3bbeeaea6d8560220f6

###
//test get by publisher_id
GET http://localhost:5000/api/annunci/publisher/1

###
//test post new
POST http://localhost:5000/api/annunci
Content-Type: application/json

{
    "id_publisher": 3,
    "title": "Nuovo annuncio",
    "description": "Descrizione del nuovo annuncio",
    "time": 1,
    "place": "Trento",
    "contact": "test@test.com"
}

###
//test update existing using id
PUT http://localhost:5000/api/annunci/645ce497d152cbb4f0a7ad4a
Content-Type: application/json

{
    "id_publisher": 1,
    "title": "ad aggiornato ancora",
    "description": "This is an updated ad",
    "time": 10,
    "place": "New Trento",
    "contact": "test@test.com"
}

###
//test delete existing using id
DELETE http://localhost:5000/api/annunci/645ce497d152cbb4f0a7ad4a