//test api registrazione
POST http://localhost:5000/api/persona/register
Content-Type: application/json

{
    "email": "persona@a.it",
    "password": "persona",
    "nome": "a",
    "cognome": "a",
    "telefono": "1",
    "dataNascita": "12/12/1999"
}

###

//test api registrazione
POST http://localhost:5000/api/attivita/register
Content-Type: application/json

{
    "email": "attivita@a.it",
    "password": "attivita",
    "nomeAttivita": "A",
    "indirizzo": "A",
    "telefono": "1",
    "partitaIVA": "1",
    "iban": "A"
}

###

//test api login
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "attivita@a.it",
    "password": "attivita"
} 



