// Get all events
GET http://localhost:5000/api/eventi

###

// Get event by ID
GET http://localhost:5000/api/eventi/647777acddfdfe452d709812

###

// Get events by publisher ID
GET http://localhost:5000/api/eventi/publisher/647237535592096d9ae27a3a

###

//add a new event
POST http://localhost:5000/api/eventi
Content-Type: application/json

{
  "titolo": "Nuovo evento 7",
  "data": "2023-05-20",
  "ora": 2,
  "indirizzo": "Trento",
  "descrizione": "Descrizione del nuovo evento 2",
  "immagini": ["image1.jpg", "image2.jpg"],
  "costo": 10,
  "posti": 100,
  "postiLiberi": 100,
  "visibilita": true,
  "categoria": "altro",
  "pubblicatore": "646893e72d12675abc29f74e",
  "utentiPrenotati": ["646893e72d12675abc29f74e", "646898f2f99185e229992f72"],
  "segnalato": false,
  "segnalazioni": []
}


###

// Update existing event by ID 
PUT http://localhost:5000/api/eventi/647777acddfdfe452d709812
Content-Type: application/json

{
    "titolo": "Evento aggiornato",
    "data": "2023-05-21",
    "ora": 2,
    "indirizzo": "New Trento",
    "descrizione": "This is an updated event",
    "immagini": ["image3.jpg"],
    "costo": 15,
    "posti": 200,
    "postiLiberi": 150,
    "visibilita": true,
    "categoria": "svago",
    "pubblicatore": "idhere",
    "utentiPrenotati": [],
    "segnalato": false,
    "segnalazioni": []
}

###

// Delete existing event by ID 
DELETE http://localhost:5000/api/eventi/647777fbddfdfe452d709816

###

// Test: Get postiLiberi
GET http://localhost:5000/api/eventi/647777acddfdfe452d709812/postiLiberi

###
// Test: Get coordinate
GET http://localhost:5000/api/eventi/647777acddfdfe452d709812/coordinate

###
// Test: Get utentiPrenotati
GET http://localhost:5000/api/eventi/647777acddfdfe452d709812/utentiPrenotati
