//test get all
GET http://localhost:5000/api/persona
###
//test get by id
GET http://localhost:5000/api/persona/645e4b0461e7233d91862f50

###
//test post new
POST http://localhost:5000/api/persona
Content-Type: application/json

{
    "email": "A",
    "password": "A",
    "nome": "A",
    "cognome": "A",
    "telefono": "A"
}

###
//test update existing using id
PATCH  http://localhost:5000/api/persona/645e4b0461e7233d91862f50
Content-Type: application/json

{
    "email": "B",
    "password": "B",
    "nome": "B",
    "cognome": "B",
    "telefono": "B"
}

###
//test delete exinsting using id
DELETE http://localhost:5000/api/persona/645e4b0461e7233d91862f50

