//test get all
GET http://localhost:5000/api/users

###
//test get by id
GET http://localhost:5000/api/users/645e941a5ab90397bf897236

###
//test post new
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "email": "F",
    "password": "F",
    "nome": "A",
    "cognome": "A",
    "telefono": "A",
    "eventiPubblicati": [1,1,1],
    "prenotazioni": [1,1,1],
    "annunciPubblicati": [1,1,1]
}

###
//test post new
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "F",
    "password": "F"
}

###
//test update existing using id
PUT http://localhost:5000/api/users/645e941a5ab90397bf897236
Content-Type: application/json

{
    "email": "B",
    "password": "B",
    "nome": "B",
    "cognome": "B",
    "telefono": "B",
    "eventiPubblicati": [2,2,2],
    "eventiPubblicati": [2,2,2],
    "prenotazioni": [2,2,2],
    "annunciPubblicati": [2,2,2]
}


###
//test delete exinsting using id
DELETE http://localhost:5000/api/users/645e941a5ab90397bf897236



