//test api registrazione
POST http://localhost:5000/api/persona/register
Content-Type: application/json

{
    "email": "test@email.it",
    "password": "email",
    "nome": "test",
    "cognome": "test",
    "telefono": "0",
    "dataNascita": "01/01/2000"
}

###

//test api login
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "test@email.it",
    "password": "email"
} 

###

//test get all users
GET http://localhost:5000/api/users

###

//test get all persona
GET http://localhost:5000/api/persona

###

//test get by id
GET http://localhost:5000/api/persona/647237535592096d9ae27a3a

###

//test get subscriptions
GET http://localhost:5000/api/persona/647237535592096d9ae27a3a/prenotazioni

###
//test update existing using id
PUT http://localhost:5000/api/persona/
Content-Type: application/json

{
    "email": "utenteTest@test.it",
    "password": "",
    "nome": "B",
    "cognome": "B",
    "telefono": "2",
    "dataNascita": "12/12/1990"
}


###
//test delete exinsting using id
DELETE http://localhost:5000/api/persona/



